version: "3.8"

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: stackit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stackit_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema_mysql.sql:/docker-entrypoint-initdb.d/schema_mysql.sql
    networks:
      - stackit-network
    command: --default-authentication-plugin=mysql_native_password

  # Spring Boot Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stackit-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stackit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - stackit-network

volumes:
  mysql_data:

networks:
  stackit-network:
    driver: bridge
